#ifndef _KERNEL_KEYBOARD_H
#define _KERNEL_KEYBOARD_H

#include <stdint.h>

/*
 * Special non-printable characters emitted for extended keys.
 * These values are in the C0 control range (< 0x20) and are never
 * generated by the normal US-QWERTY keymap, so they are safe to use
 * as sentinels in keyboard_getchar() callers.
 */
#define KEY_ARROW_UP    '\x01'   /* PS/2 extended scan code E0 48 */
#define KEY_ARROW_DOWN  '\x02'   /* PS/2 extended scan code E0 50 */

// Initialise the PS/2 keyboard driver and register the IRQ1 handler.
void keyboard_init(void);

// Block until a character is available, then return it.
char keyboard_getchar(void);

// Return the next character from the ring buffer, or 0 if the buffer is empty.
char keyboard_poll(void);

#endif // _KERNEL_KEYBOARD_H
