/*
 * vics.c — VICS interactive text editor for Makar.
 *
 * Ported from the Medli VICS text editor (C# original) to a bare-metal C
 * implementation that runs directly in the Makar kernel shell.
 *
 * Design constraints:
 *   - No dynamic allocation after startup: the line buffer is file-scope BSS.
 *   - Writes directly to VGA text memory (0xB8000) for low-latency redraws;
 *     also mirrors each cell to the VESA framebuffer when it is active.
 *   - All key input goes through keyboard_getchar().
 */

#include <kernel/vics.h>
#include <kernel/vfs.h>
#include <kernel/vga.h>
#include <kernel/tty.h>
#include <kernel/keyboard.h>
#include <kernel/heap.h>
#include <kernel/vesa_tty.h>
#include <string.h>

/* -------------------------------------------------------------------------
 * Tunable limits
 * ---------------------------------------------------------------------- */

#define VICS_TEXT_ROWS   24          /* rows 0-23 hold editable content     */
#define VICS_STATUS_ROW  24          /* row 24 is the status bar            */
#define VICS_MAX_LINES   256         /* maximum number of editable lines     */
#define VICS_LINE_CAP    80          /* maximum chars per line (no NUL)      */
#define VICS_FILE_MAX    (64u * 1024u) /* max file size for load/save        */

/* -------------------------------------------------------------------------
 * Color attributes
 * ---------------------------------------------------------------------- */

/* White text on black background — editor body */
#define VICS_CLR_TEXT    0x07u
/* Black text on light-grey background — status bar (reverse video) */
#define VICS_CLR_STATUS  0x70u
/* Light-red text on black — unsaved-changes warning in status bar */
#define VICS_CLR_WARN    make_color(COLOR_LIGHT_RED, COLOR_BLACK)

/* Shell color scheme (mirrored from shell_priv.h to avoid the include) */
#define VICS_SHELL_VGA   0x1Fu       /* white on blue                       */
#define VICS_SHELL_FG    0xFFFFFFu   /* RGB foreground for VESA             */
#define VICS_SHELL_BG    0x0000AAu   /* RGB background for VESA             */

/* -------------------------------------------------------------------------
 * Ctrl-key sentinels (generated by keyboard.c when Ctrl is held)
 * ---------------------------------------------------------------------- */

#define CTRL_S  '\x13'   /* Ctrl+S = save  */
#define CTRL_Q  '\x11'   /* Ctrl+Q = quit  */

/* -------------------------------------------------------------------------
 * Editor state  (file-scope statics — never on the kernel stack)
 * ---------------------------------------------------------------------- */

static char v_lines[VICS_MAX_LINES][VICS_LINE_CAP + 1]; /* +1 for NUL      */
static int  v_len  [VICS_MAX_LINES];   /* current length of each line        */
static int  v_nlines;                  /* total number of lines in buffer    */
static int  v_cur_row;                 /* cursor row  (absolute, 0-based)    */
static int  v_cur_col;                 /* cursor col  (0-based)              */
static int  v_view_top;                /* first visible line                 */
static int  v_dirty;                   /* 1 = unsaved changes                */
static int  v_quit_warn;              /* 1 = first ^Q pressed, warn shown   */
static char v_path[VFS_PATH_MAX];      /* file path (empty = unnamed buffer) */

/* -------------------------------------------------------------------------
 * Low-level display helpers
 * ---------------------------------------------------------------------- */

/*
 * Write character c at (col, row) with the given VGA colour attribute.
 * If a VESA framebuffer is active the caller must set the VESA colour via
 * vesa_tty_setcolor() before the first cell in each row.
 */
static inline void vics_put(int col, int row, char c, uint8_t clr)
{
    VGA_MEMORY[row * VGA_WIDTH + col] = make_vgaentry(c, clr);
    if (vesa_tty_is_ready())
        vesa_tty_put_at(c, (uint32_t)col, (uint32_t)row);
}

/* Render one text row on screen from the line buffer. */
static void vics_draw_line(int screen_row, int line_idx)
{
    const char *s   = (line_idx < v_nlines) ? v_lines[line_idx] : NULL;
    int         len = s ? v_len[line_idx] : 0;

    if (vesa_tty_is_ready())
        vesa_tty_setcolor(0xFFFFFFu, 0x000000u);   /* white on black */

    for (int col = 0; col < VGA_WIDTH; col++) {
        char ch = (col < len) ? s[col] : ' ';
        vics_put(col, screen_row, ch, VICS_CLR_TEXT);
    }
}

/* Simple unsigned-integer → decimal string (buf must be ≥ 12 bytes). */
static void vics_uitoa(unsigned int v, char *buf)
{
    if (v == 0) { buf[0] = '0'; buf[1] = '\0'; return; }
    char tmp[12]; int i = 0;
    while (v) { tmp[i++] = (char)('0' + v % 10); v /= 10; }
    int j = 0;
    while (i > 0) buf[j++] = tmp[--i];
    buf[j] = '\0';
}

/* Append string s into buf[0..cap-1] starting at *off (NUL-terminates). */
static void vics_append(char *buf, int cap, int *off, const char *s)
{
    while (*s && *off < cap - 1) buf[(*off)++] = *s++;
    buf[*off] = '\0';
}

/* Render the status bar (row 24). */
static void vics_draw_status(void)
{
    char bar[VGA_WIDTH + 1];
    int  off = 0;

    if (v_quit_warn) {
        /* Full-width warning message. */
        vics_append(bar, (int)sizeof(bar), &off,
                    " Unsaved! Press ^Q again to quit, or ^S to save. ");
    } else {
        vics_append(bar, (int)sizeof(bar), &off, " VICS | ");
        vics_append(bar, (int)sizeof(bar), &off, v_path[0] ? v_path : "[new]");
        if (v_dirty)
            vics_append(bar, (int)sizeof(bar), &off, " [+]");
        vics_append(bar, (int)sizeof(bar), &off, " | Ln ");
        char tmp[12];
        vics_uitoa((unsigned int)(v_cur_row + 1), tmp);
        vics_append(bar, (int)sizeof(bar), &off, tmp);
        vics_append(bar, (int)sizeof(bar), &off, "/");
        vics_uitoa((unsigned int)v_nlines, tmp);
        vics_append(bar, (int)sizeof(bar), &off, tmp);
        vics_append(bar, (int)sizeof(bar), &off, " | ^S:Save  ^Q:Quit");
    }

    /* Pad to full width. */
    while (off < VGA_WIDTH) bar[off++] = ' ';
    bar[VGA_WIDTH] = '\0';

    uint8_t clr = v_quit_warn ? VICS_CLR_WARN : VICS_CLR_STATUS;

    if (vesa_tty_is_ready()) {
        /* Approximate VESA status-bar colour. */
        if (v_quit_warn)
            vesa_tty_setcolor(0xFF0000u, 0x000000u);
        else
            vesa_tty_setcolor(0x000000u, 0xAAAAAAu);
    }

    for (int col = 0; col < VGA_WIDTH; col++)
        vics_put(col, VICS_STATUS_ROW, bar[col], clr);
}

/* Redraw the full screen and update the hardware cursor. */
static void vics_redraw(void)
{
    for (int r = 0; r < VICS_TEXT_ROWS; r++)
        vics_draw_line(r, v_view_top + r);
    vics_draw_status();
    update_cursor((size_t)(v_cur_row - v_view_top), (size_t)v_cur_col);
}

/* -------------------------------------------------------------------------
 * Navigation helpers
 * ---------------------------------------------------------------------- */

/* Clamp v_cur_col to the actual line length. */
static void vics_clamp_col(void)
{
    int max = (v_cur_row < v_nlines) ? v_len[v_cur_row] : 0;
    if (v_cur_col > max) v_cur_col = max;
}

/* Scroll v_view_top so that v_cur_row is visible. */
static void vics_scroll(void)
{
    if (v_cur_row < v_view_top)
        v_view_top = v_cur_row;
    else if (v_cur_row >= v_view_top + VICS_TEXT_ROWS)
        v_view_top = v_cur_row - VICS_TEXT_ROWS + 1;
}

/* -------------------------------------------------------------------------
 * Editing operations
 * ---------------------------------------------------------------------- */

/* Insert character c at the current cursor position. */
static void vics_insert_char(char c)
{
    if (v_cur_row >= VICS_MAX_LINES) return;

    /* Extend buffer with empty lines if past the last line. */
    while (v_nlines <= v_cur_row) {
        v_lines[v_nlines][0] = '\0';
        v_len[v_nlines]       = 0;
        v_nlines++;
    }

    char *line = v_lines[v_cur_row];
    int   len  = v_len[v_cur_row];

    if (len >= VICS_LINE_CAP) return;  /* line full */

    /* Shift chars right from cursor. */
    for (int i = len; i > v_cur_col; i--)
        line[i] = line[i - 1];
    line[v_cur_col]  = c;
    line[len + 1]    = '\0';
    v_len[v_cur_row] = len + 1;
    v_cur_col++;
    v_dirty = 1;
}

/* Delete the character before the cursor (backspace). */
static void vics_backspace(void)
{
    if (v_cur_row == 0 && v_cur_col == 0) return;

    if (v_cur_col > 0) {
        /* Delete to the left on the same line. */
        char *line = v_lines[v_cur_row];
        int   len  = v_len[v_cur_row];
        for (int i = v_cur_col - 1; i < len - 1; i++)
            line[i] = line[i + 1];
        line[len - 1]    = '\0';
        v_len[v_cur_row] = len - 1;
        v_cur_col--;
    } else {
        /* Join the current line onto the end of the previous line. */
        int prev     = v_cur_row - 1;
        int prev_len = v_len[prev];
        int cur_len  = v_len[v_cur_row];

        if (prev_len + cur_len > VICS_LINE_CAP)
            return;  /* combined line would be too long */

        memcpy(v_lines[prev] + prev_len, v_lines[v_cur_row],
               (size_t)(cur_len + 1));
        v_len[prev] = prev_len + cur_len;

        /* Remove the current line by shifting everything down. */
        for (int i = v_cur_row; i < v_nlines - 1; i++) {
            memcpy(v_lines[i], v_lines[i + 1],
                   (size_t)(v_len[i + 1] + 1));
            v_len[i] = v_len[i + 1];
        }
        v_nlines--;
        v_cur_row = prev;
        v_cur_col = prev_len;
    }
    v_dirty = 1;
}

/* Split the current line at the cursor (insert newline). */
static void vics_newline(void)
{
    if (v_nlines >= VICS_MAX_LINES) return;

    /* Ensure the current row exists. */
    while (v_nlines <= v_cur_row) {
        v_lines[v_nlines][0] = '\0';
        v_len[v_nlines]       = 0;
        v_nlines++;
    }

    int  cur_len   = v_len[v_cur_row];
    int  right_len = cur_len - v_cur_col;

    /* Shift all lines after v_cur_row down by one. */
    for (int i = v_nlines; i > v_cur_row + 1; i--) {
        memcpy(v_lines[i], v_lines[i - 1], (size_t)(v_len[i - 1] + 1));
        v_len[i] = v_len[i - 1];
    }

    /* New line gets the right portion of the current line. */
    memcpy(v_lines[v_cur_row + 1], v_lines[v_cur_row] + v_cur_col,
           (size_t)(right_len + 1));
    v_len[v_cur_row + 1] = right_len;

    /* Current line is truncated to the left portion. */
    v_lines[v_cur_row][v_cur_col] = '\0';
    v_len[v_cur_row]               = v_cur_col;

    v_nlines++;
    v_cur_row++;
    v_cur_col = 0;
    v_dirty   = 1;
}

/* -------------------------------------------------------------------------
 * File I/O
 * ---------------------------------------------------------------------- */

/* Parse a flat byte buffer into the line array; resets all cursor state. */
static void vics_parse(const char *buf, uint32_t size)
{
    v_nlines   = 0;
    v_cur_row  = 0;
    v_cur_col  = 0;
    v_view_top = 0;
    v_dirty    = 0;
    v_quit_warn = 0;

    uint32_t pos = 0;
    while (v_nlines < VICS_MAX_LINES) {
        uint32_t start = pos;
        while (pos < size && buf[pos] != '\n') pos++;

        int len = (int)(pos - start);
        if (len > VICS_LINE_CAP) len = VICS_LINE_CAP;

        memcpy(v_lines[v_nlines], buf + start, (size_t)len);
        v_lines[v_nlines][len] = '\0';
        v_len[v_nlines]        = len;
        v_nlines++;

        if (pos >= size) break;
        pos++;  /* skip '\n' */
    }

    /* Guarantee at least one (possibly empty) line. */
    if (v_nlines == 0) {
        v_lines[0][0] = '\0';
        v_len[0]      = 0;
        v_nlines      = 1;
    }
}

/*
 * Build a flat buffer containing all lines joined by '\n'.
 * Returns a heap-allocated buffer and sets *out_size.
 * The caller must kfree() the buffer.
 * Returns NULL on allocation failure.
 */
static char *vics_flatten(uint32_t *out_size)
{
    uint32_t total = 0;
    for (int i = 0; i < v_nlines; i++)
        total += (uint32_t)v_len[i] + 1u;  /* +1 for '\n' (last line: +1 spare) */
    /* Last line has no trailing '\n', so subtract 1. */
    if (total > 0) total--;

    char *buf = (char *)kmalloc(total + 1u);
    if (!buf) return NULL;

    uint32_t off = 0;
    for (int i = 0; i < v_nlines; i++) {
        memcpy(buf + off, v_lines[i], (size_t)v_len[i]);
        off += (uint32_t)v_len[i];
        if (i < v_nlines - 1)
            buf[off++] = '\n';
    }
    buf[off] = '\0';
    *out_size = off;
    return buf;
}

/* Save the buffer to disk.  Returns 0 on success, -1 on error. */
static int vics_save(void)
{
    if (!v_path[0]) return -1;  /* unnamed buffer */

    uint32_t size = 0;
    char    *buf  = vics_flatten(&size);
    if (!buf) return -1;

    int err = vfs_write_file(v_path, buf, size);
    kfree(buf);
    if (err == 0) v_dirty = 0;
    return err;
}

/* -------------------------------------------------------------------------
 * Public entry point
 * ---------------------------------------------------------------------- */

void vics_edit(const char *path)
{
    /* Store path. */
    if (path && *path) {
        strncpy(v_path, path, VFS_PATH_MAX - 1);
        v_path[VFS_PATH_MAX - 1] = '\0';
    } else {
        v_path[0] = '\0';
    }

    /* Load file (a missing / unreadable file starts an empty buffer). */
    uint8_t *file_buf = (uint8_t *)kmalloc(VICS_FILE_MAX);
    if (file_buf) {
        uint32_t got = 0;
        if (v_path[0] &&
            vfs_read_file(v_path, file_buf, VICS_FILE_MAX, &got) == 0 &&
            got > 0)
            vics_parse((const char *)file_buf, got);
        else
            vics_parse("", 0);
        kfree(file_buf);
    } else {
        vics_parse("", 0);
    }

    /* -----------------------------------------------------------------------
     * Main editing loop
     * -------------------------------------------------------------------- */
    for (;;) {
        vics_scroll();
        vics_redraw();

        char c = keyboard_getchar();

        /* ---- Quit ---- */
        if (c == CTRL_Q) {
            if (!v_dirty || v_quit_warn)
                break;              /* clean, or user confirmed */
            v_quit_warn = 1;       /* show warning; wait for second ^Q */
            continue;
        }
        v_quit_warn = 0;           /* any other key clears the warning */

        /* ---- Save ---- */
        if (c == CTRL_S) {
            if (v_path[0]) {
                vics_save();       /* status bar reflects v_dirty on next draw */
            }
            /* If no path, the status bar already shows "[new]" as a hint. */
            continue;
        }

        /* ---- Navigation ---- */
        if (c == KEY_ARROW_UP) {
            if (v_cur_row > 0) { v_cur_row--; vics_clamp_col(); }
            continue;
        }
        if (c == KEY_ARROW_DOWN) {
            if (v_cur_row < v_nlines - 1) { v_cur_row++; vics_clamp_col(); }
            continue;
        }
        if (c == KEY_ARROW_LEFT) {
            if (v_cur_col > 0) {
                v_cur_col--;
            } else if (v_cur_row > 0) {
                v_cur_row--;
                v_cur_col = v_len[v_cur_row];
            }
            continue;
        }
        if (c == KEY_ARROW_RIGHT) {
            if (v_cur_col < v_len[v_cur_row]) {
                v_cur_col++;
            } else if (v_cur_row < v_nlines - 1) {
                v_cur_row++;
                v_cur_col = 0;
            }
            continue;
        }

        /* ---- Editing ---- */
        if (c == '\b')              { vics_backspace();  continue; }
        if (c == '\n' || c == '\r') { vics_newline();    continue; }
        if (c >= ' ' && c <= '~')   { vics_insert_char(c); continue; }

        /* All other characters (e.g. Tab, remaining Ctrl codes) are ignored. */
    }

    /* -----------------------------------------------------------------------
     * Restore the shell colour scheme after the editor exits.
     * terminal_set_colorscheme clears the VGA screen and resets t_row/t_column.
     * ---------------------------------------------------------------------- */
    terminal_set_colorscheme(VICS_SHELL_VGA);
    if (vesa_tty_is_ready()) {
        vesa_tty_setcolor(VICS_SHELL_FG, VICS_SHELL_BG);
        vesa_tty_clear();
    }
}
