#!/usr/bin/env python3
"""Generate src/kernel/include/kernel/logo.h from hard-coded ASCII art.

No external dependencies — stdlib only.

Each art character is a 7×7 grid of '#' (foreground) and ' ' (background).
PIXEL_SCALE enlarges each art pixel to a PIXEL_SCALE×PIXEL_SCALE screen-pixel
block.  Output is a 1-bpp packed bitmap, MSB first, rows padded to the next
byte boundary.
"""

import os

# ---------------------------------------------------------------------------
# Block-pixel font  (7 cols × 7 rows per glyph, all strings exactly 7 chars)
# ---------------------------------------------------------------------------
FONT = {
    'M': [
        "#     #",
        "##   ##",
        "# # # #",
        "#  #  #",
        "#     #",
        "#     #",
        "#     #",
    ],
    'A': [
        "  ###  ",
        " #   # ",
        "#     #",
        "#######",
        "#     #",
        "#     #",
        "#     #",
    ],
    'K': [
        "#     #",
        "#    # ",
        "#   #  ",
        "####   ",
        "#   #  ",
        "#    # ",
        "#     #",
    ],
    'R': [
        "###### ",
        "#     #",
        "#     #",
        "###### ",
        "#  #   ",
        "#   #  ",
        "#    ##",
    ],
}

WORD        = "MAKAR"
CHAR_GAP    = 2     # art-pixel columns between letters
PIXEL_SCALE = 10    # each art pixel → PIXEL_SCALE × PIXEL_SCALE screen pixels
CHAR_H      = 7
CHAR_W      = 7

# ---------------------------------------------------------------------------
# Assemble the art grid
# ---------------------------------------------------------------------------
art_rows = []
for row_i in range(CHAR_H):
    row = ""
    for i, ch in enumerate(WORD):
        row += FONT[ch][row_i]
        if i < len(WORD) - 1:
            row += " " * CHAR_GAP
    art_rows.append(row)

art_w = len(art_rows[0])

# Sanity-check all rows are the same width
for r in art_rows:
    assert len(r) == art_w, f"Row length mismatch: {len(r)} vs {art_w}: '{r}'"

logo_w = art_w * PIXEL_SCALE
logo_h = CHAR_H  * PIXEL_SCALE

# ---------------------------------------------------------------------------
# Pack into 1-bpp bitmap (MSB first, rows padded to byte boundary)
# ---------------------------------------------------------------------------
stride = (logo_w + 7) // 8
bits   = bytearray(stride * logo_h)

for art_y, row_str in enumerate(art_rows):
    for art_x, ch in enumerate(row_str):
        if ch != '#':
            continue
        for dy in range(PIXEL_SCALE):
            for dx in range(PIXEL_SCALE):
                px = art_x * PIXEL_SCALE + dx
                py = art_y * PIXEL_SCALE + dy
                byte_i = py * stride + px // 8
                bits[byte_i] |= 1 << (7 - px % 8)

# ---------------------------------------------------------------------------
# Emit C header
# ---------------------------------------------------------------------------
lines = [
    "/* AUTO-GENERATED by tools/gen_logo.py — do not edit by hand. */",
    "#ifndef KERNEL_LOGO_H",
    "#define KERNEL_LOGO_H",
    "#include <stdint.h>",
    "",
    f"#define LOGO_WIDTH  {logo_w}u",
    f"#define LOGO_HEIGHT {logo_h}u",
    f"#define LOGO_STRIDE {stride}u  /* packed bytes per row */",
    "",
    "/* 1-bpp bitmap, MSB first.  Bit=1 means foreground pixel. */",
    "static const uint8_t logo_bits[] = {",
]

COLS = 12
for i in range(0, len(bits), COLS):
    chunk   = bits[i : i + COLS]
    vals    = ", ".join(f"0x{b:02X}" for b in chunk)
    comma   = "," if i + COLS < len(bits) else ""
    lines.append(f"    {vals}{comma}")

lines += ["};", "", "#endif /* KERNEL_LOGO_H */", ""]

out_path = os.path.normpath(
    os.path.join(os.path.dirname(__file__),
                 "../src/kernel/include/kernel/logo.h"))

with open(out_path, "w") as f:
    f.write("\n".join(lines))

print(f"Generated {out_path}")
print(f"  logo size : {logo_w} × {logo_h} px")
print(f"  bitmap    : {len(bits)} bytes  ({stride} bytes/row)")
